export { ReactComponent as IconAdd } from './icon-add.svg';
export { ReactComponent as IconArrowDown } from './icon-arrow-down.svg';
export { ReactComponent as IconArrowLeft } from './icon-arrow-left.svg';
export { ReactComponent as IconArrowUp } from './icon-arrow-up.svg';
export { ReactComponent as IconCheck } from './icon-check.svg';
export { ReactComponent as IconComments } from './icon-comments.svg';
export { ReactComponent as IconEditFeedback } from './icon-edit-feedback.svg';
export { ReactComponent as IconNewFeedback } from './icon-new-feedback.svg';
export { ReactComponent as IconPlus } from './icon-plus.svg';
